files added
OSAMA478/03-css-border-animation pull request #1
Opened 2022-02-02 05:25 UTC by OSAMA478

2022-02-02 11:42 UTC, mujeeb100 approved these changes
lgtm

2022-02-03 15:23 UTC, syedabdullahali reviewed
nice

2022-02-03 15:23 UTC, syedabdullahali approved these changes

2022-02-06 10:46 UTC, nehalskdev requested changes
check comments.

2022-02-06 10:46 UTC, nehalskdev commented on index.html
> +					<img src="tiktok.png" alt="" />
add alt do not leave it blank

2022-02-06 10:46 UTC, nehalskdev commented on style.css
> +	align-items: center;
```suggestion
	display: grid;
	place-items: center;
```
you can do this task in 2 line

2022-02-06 10:46 UTC, nehalskdev commented on style.css
> +	/* background: #ffffff; */
why comment?

2022-02-18 04:00 UTC, merged